spring:
  application:
    name: booking-service
  profiles:
    active: optimistic   # switch to: pessimistic | optimistic | redis (later stages)

  datasource:
    url: jdbc:postgresql://localhost:5433/booking
    username: booking
    password: booking
    hikari:
      maximum-pool-size: 50

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    dev.booking: INFO
